### PR TITLE
Rework

### PR DESCRIPTION
**Pull request by constantinius**
This is a major refactoring of the TimeSlider with the aim to:
- disentangle source
- remove unused stuff
- improve readability, examples, documentation
### Concise naming of concepts

These naming conventions are employed in the code and documentation
- TimeSlider - the timeslider object itself
- Dataset - a set of records from the same source with parameters applied (like color)
- Source - a dynamic source of records (either via AJAX or something else)
- Record - a single record displayed on the timeslider either as a point or a range
- Element - a DOM element
### Static building of `d3.timeslider.js`

When a bundle is created, this is now done using Browserify that also bundles all dependencies (like d3)
### Modularization

It is now possible to `require` d3.timeslider and its plugins.
#### Sources must now conform to the new `Source` interface:

They must either be a `function` that supports the following parameters:
- `start`, `end`, `params`, `callback` (two parameters `records`, `paths`)
- or they must have a `fetch` method using the same parameters
- or be `null` (in that case, statically supplied `records` will be used)
#### The `coverageselected` event is now called `recordClicked`

And the event detail object now has the following values:
- `start`
- `end`
- `dataset` - the dataset ID
- `params` - an optional hash. see below
#### Records are now different

Records are now either:
- a single `Date`
- an `Array` of one or two `Date`s and  _optionally_ an additional parameters `Object`.

The parameters can be used for filtering and if it has an `id` or `name`, it is shown as a tooltip when hovering the record.

Example with all possible options:

``` javascript
var timeSlider = new TimeSlider(document.getElementById('d3_timeslider'), {
    // ... other options
    datasets: [{
        id: 'test',
        color: 'magenta',
        records: [
            // single Date object
            new Date("2012-01-03T12:00:00Z"),
            // single Date object within Array
            [ new Date("2012-01-02T12:00:00Z") ],
            // single Date object with parameters
            [ new Date("2012-01-03T12:00:00Z"), {someParam: 1234, id: "this will be shown as tooltip"}],
            // two Date objects
            [ new Date("2012-01-06T12:00:00Z"), new Date("2012-01-06T16:00:00Z")],
            // two Date objects with parameters
            [ new Date("2012-01-01T12:00:00Z"), new Date("2012-01-01T16:00:00Z"), {testParam: false, name: "this will also be shown as tooltip"} ],
        ]
    }],
    // ...
});
```
#### Record filtering

Occurrences of geographic bounding boxes have been removed. Instead a global function can be installed via `timeslider.setRecordFilter(filterFunc)`. The filter function is called for each record upon drawing and shall return a boolean value, indicating whether it is shown fully (true) or hollow (false). This can be used to make bounding box checks using the bounding box from the records parameters.

Example:

``` javascript
var timeSlider = new TimeSlider(document.getElementById('timeSlider'), {
    // ... other options
    datasets: [{
        id: 'test',
        color: 'red',
        records: null,
        source: { fetch: function(start, end, params, callback) {
            callback([
                [ new Date("2012-01-01T12:00:00Z"), new Date("2012-01-01T16:00:00Z"), {visible: false} ],
                [ new Date("2012-01-02T12:00:00Z"), {visible: true}],
                [ new Date("2012-01-03T12:00:00Z"), {visible: false}],
                new Date("2012-01-03T12:00:00Z"),
                [ new Date("2012-01-05T00:00:00Z"), new Date("2012-01-06T00:00:00Z"), {visible: false}],
                [ new Date("2012-01-06T12:00:00Z"), new Date("2012-01-06T16:00:00Z")],
            ]);
        }}
    }],

    recordFilter: function(record, dataset) {
        var params = record[2];
        if (params && params.hasOwnProperty("visible")) {
            return params.visible;
        }
        return true;
    }
});
```

### CODE REVIEW

**Comment by santilland** [comment]
Seems like some nice changes of necessary things that needed to be done, i did not know that this was critical right now. For now i would mark this as [WIP] as not all functionality has been ported and merging could break multiple dependencies. Merging this would mean a release number bump i guess.
I still have not enough experience with browserify but i strongly disencourage from building d3 into the timeslider library unless browserify can disentangle and understand build dependencies and separate them into their core components requiring this in another project which uses d3 would mean integrating d3 twice. I have seen in other projects building the dependencies into one separate file, i guess this would also be a possibility.

**Comment by constantinius** [comment]
Yes, you are right it is still WiP. Until all previous functionalities are ported this will nit be merged. I give a preview of the changes as basis for further diacussion.
Regarding the second part of your remarks: the lib will be able to be used in two ways:
 * as a standalone bundle built with browserify (this includes d3) and is meant as starting point to add a timeslider to your page without hassling with dependencies.
 * as a library that can be required by client code. In this case, the dependencies will be installed when using ``npm install`` and bundled however the client lib wants it. I'm using webpack in another project and dependency resolution worka fine. (In special cases, like when two libs require different versions of a single dependency, you have to make shims manually)
Is this more clear now?

**Comment by constantinius** [comment]
Now WMS and WPS (EOxServer: "getTimeData" process) sources are implemented and working again.
I consider this PR complete, but please check if thats the case for everyone.

**Comment by santilland** [comment]
I introduced in a not to clean way the visualization of line plots in the time slider and it was probably overlooked, i guess this should be also considered for porting and should probably be separated more cleanly, maybe as  specific process or similar, would need to look closer into the new refactoring to see what would be the best way.
In any case i considered that we specifiy specific releases in projects that depend on the timeslider so i guess we can play around with a major release now even if not all functionality is there.
It would probably make sense to change how we do the releases as i think that we use a somewhat outdated approach in the timeslider library.

**Comment by constantinius** [comment]
@santilland The line datasets should now work again. Please check your integrations so that we can close this PR.

**Pull request merged**
